# -*- coding: utf-8 -*-
"""RA2211003011310_DS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJiNt4wID9920kAj-GRFL72c0Rxx1E00
"""

# prompt: Create an array and perform the following operations : ndim , itemsize, dtype, reshape, slicing, linspace, ravel.

import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Array dimensions
print("Dimensions:", arr.ndim)

# Size of each element in bytes
print("Item size:", arr.itemsize)

# Data type of the array elements
print("Data type:", arr.dtype)

# Reshape the array
reshaped_arr = arr.reshape(2, 5)
print("Reshaped array:\n", reshaped_arr)

# Array slicing
sliced_arr = arr[2:5]  # Elements from index 2 up to (but not including) 5
print("Sliced array:", sliced_arr)


# Create an array using linspace
linspace_arr = np.linspace(0, 1, 5)  # 5 evenly spaced numbers between 0 and 1
print("Linspace array:", linspace_arr)

# Flatten the array using ravel
flattened_arr = reshaped_arr.ravel()
print("Flattened array:", flattened_arr)

